# Makefile per l'esercizio 3.2

# Compilazione
all: Lexer.class

Lexer.class: Lexer.java
	javac Lexer.java

# Esecuzione
run: Lexer.class
	java Lexer

# Pulizia
clean:
	rm -f *.class

.PHONY: all run clean
